packages:
  - apps/*

minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "fallow*"
  - "@fallow-cli/**"

peerDependencyRules:
  allowedVersions:
    esbuild: 0.25.12

allowBuilds:
  esbuild: true
  msw: false
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
