/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
import { geometryColumn } from "@payloadcms/db-postgres";
export const enum__locales = pgEnum("enum__locales", ["es", "en"]);
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "editor",
  "validation-manager",
]);
export const enum_places_access_type = pgEnum("enum_places_access_type", [
  "open",
  "private",
  "restricted",
]);
export const enum_places_status = pgEnum("enum_places_status", [
  "draft",
  "published",
]);
export const enum__places_v_version_access_type = pgEnum(
  "enum__places_v_version_access_type",
  ["open", "private", "restricted"],
);
export const enum__places_v_version_status = pgEnum(
  "enum__places_v_version_status",
  ["draft", "published"],
);
export const enum__places_v_published_locale = pgEnum(
  "enum__places_v_published_locale",
  ["es", "en"],
);
export const enum_articles_difficulty = pgEnum("enum_articles_difficulty", [
  "beginner",
  "intermediate",
  "advanced",
]);
export const enum_articles_status = pgEnum("enum_articles_status", [
  "draft",
  "published",
]);
export const enum__articles_v_version_difficulty = pgEnum(
  "enum__articles_v_version_difficulty",
  ["beginner", "intermediate", "advanced"],
);
export const enum__articles_v_version_status = pgEnum(
  "enum__articles_v_version_status",
  ["draft", "published"],
);
export const enum__articles_v_published_locale = pgEnum(
  "enum__articles_v_published_locale",
  ["es", "en"],
);
export const enum_products_stock_status = pgEnum("enum_products_stock_status", [
  "available",
  "unavailable",
]);
export const enum_products_status = pgEnum("enum_products_status", [
  "draft",
  "published",
]);
export const enum__products_v_version_stock_status = pgEnum(
  "enum__products_v_version_stock_status",
  ["available", "unavailable"],
);
export const enum__products_v_version_status = pgEnum(
  "enum__products_v_version_status",
  ["draft", "published"],
);
export const enum__products_v_published_locale = pgEnum(
  "enum__products_v_published_locale",
  ["es", "en"],
);
export const enum_site_settings_member_identifier_type = pgEnum(
  "enum_site_settings_member_identifier_type",
  ["generic", "cl_rut"],
);
export const enum_home_page_status = pgEnum("enum_home_page_status", [
  "draft",
  "published",
]);
export const enum__home_page_v_version_status = pgEnum(
  "enum__home_page_v_version_status",
  ["draft", "published"],
);
export const enum__home_page_v_published_locale = pgEnum(
  "enum__home_page_v_published_locale",
  ["es", "en"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    role: enum_users_role("role").notNull().default("admin"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const memberships = pgTable(
  "memberships",
  {
    id: serial("id").primaryKey(),
    identifier: varchar("identifier").notNull(),
    normalizedIdentifier: varchar("normalized_identifier").notNull(),
    lookupHash: varchar("lookup_hash").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    notes: varchar("notes"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("memberships_normalized_identifier_idx").on(
      columns.normalizedIdentifier,
    ),
    uniqueIndex("memberships_lookup_hash_idx").on(columns.lookupHash),
    index("memberships_updated_at_idx").on(columns.updatedAt),
    index("memberships_created_at_idx").on(columns.createdAt),
  ],
);

export const _memberships_v = pgTable(
  "_memberships_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => memberships.id, {
      onDelete: "set null",
    }),
    version_identifier: varchar("version_identifier").notNull(),
    version_normalizedIdentifier: varchar(
      "version_normalized_identifier",
    ).notNull(),
    version_lookupHash: varchar("version_lookup_hash").notNull(),
    version_isActive: boolean("version_is_active").notNull().default(true),
    version_notes: varchar("version_notes"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("_memberships_v_parent_idx").on(columns.parent),
    index("_memberships_v_version_version_normalized_identifier_idx").on(
      columns.version_normalizedIdentifier,
    ),
    index("_memberships_v_version_version_lookup_hash_idx").on(
      columns.version_lookupHash,
    ),
    index("_memberships_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_memberships_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_memberships_v_created_at_idx").on(columns.createdAt),
    index("_memberships_v_updated_at_idx").on(columns.updatedAt),
  ],
);

export const places = pgTable(
  "places",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug"),
    accessType: enum_places_access_type("access_type").default("open"),
    region: varchar("region"),
    city: varchar("city"),
    externalUrl: varchar("external_url"),
    location: geometryColumn("location"),
    sourceUrl: varchar("source_url"),
    sourceUpdatedAt: timestamp("source_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_places_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("places_slug_idx").on(columns.slug),
    index("places_updated_at_idx").on(columns.updatedAt),
    index("places_created_at_idx").on(columns.createdAt),
    index("places__status_idx").on(columns._status),
  ],
);

export const places_locales = pgTable(
  "places_locales",
  {
    title: varchar("title"),
    summary: varchar("summary"),
    body: jsonb("body"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("places_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [places.id],
      name: "places_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _places_v = pgTable(
  "_places_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => places.id, {
      onDelete: "set null",
    }),
    version_slug: varchar("version_slug"),
    version_accessType: enum__places_v_version_access_type(
      "version_access_type",
    ).default("open"),
    version_region: varchar("version_region"),
    version_city: varchar("version_city"),
    version_externalUrl: varchar("version_external_url"),
    version_location: geometryColumn("version_location"),
    version_sourceUrl: varchar("version_source_url"),
    version_sourceUpdatedAt: timestamp("version_source_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__places_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__places_v_published_locale("published_locale"),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => [
    index("_places_v_parent_idx").on(columns.parent),
    index("_places_v_version_version_slug_idx").on(columns.version_slug),
    index("_places_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_places_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_places_v_version_version__status_idx").on(columns.version__status),
    index("_places_v_created_at_idx").on(columns.createdAt),
    index("_places_v_updated_at_idx").on(columns.updatedAt),
    index("_places_v_snapshot_idx").on(columns.snapshot),
    index("_places_v_published_locale_idx").on(columns.publishedLocale),
    index("_places_v_latest_idx").on(columns.latest),
    index("_places_v_autosave_idx").on(columns.autosave),
  ],
);

export const _places_v_locales = pgTable(
  "_places_v_locales",
  {
    version_title: varchar("version_title"),
    version_summary: varchar("version_summary"),
    version_body: jsonb("version_body"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_places_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_places_v.id],
      name: "_places_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug"),
    category: varchar("category"),
    difficulty: enum_articles_difficulty("difficulty").default("beginner"),
    reviewedAt: timestamp("reviewed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    sourceUrl: varchar("source_url"),
    sourceUpdatedAt: timestamp("source_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_articles_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("articles_slug_idx").on(columns.slug),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
    index("articles__status_idx").on(columns._status),
  ],
);

export const articles_locales = pgTable(
  "articles_locales",
  {
    title: varchar("title"),
    body: jsonb("body"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("articles_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [articles.id],
      name: "articles_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _articles_v = pgTable(
  "_articles_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => articles.id, {
      onDelete: "set null",
    }),
    version_slug: varchar("version_slug"),
    version_category: varchar("version_category"),
    version_difficulty:
      enum__articles_v_version_difficulty("version_difficulty").default(
        "beginner",
      ),
    version_reviewedAt: timestamp("version_reviewed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_sourceUrl: varchar("version_source_url"),
    version_sourceUpdatedAt: timestamp("version_source_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__articles_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__articles_v_published_locale("published_locale"),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => [
    index("_articles_v_parent_idx").on(columns.parent),
    index("_articles_v_version_version_slug_idx").on(columns.version_slug),
    index("_articles_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_articles_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_articles_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_articles_v_created_at_idx").on(columns.createdAt),
    index("_articles_v_updated_at_idx").on(columns.updatedAt),
    index("_articles_v_snapshot_idx").on(columns.snapshot),
    index("_articles_v_published_locale_idx").on(columns.publishedLocale),
    index("_articles_v_latest_idx").on(columns.latest),
    index("_articles_v_autosave_idx").on(columns.autosave),
  ],
);

export const _articles_v_locales = pgTable(
  "_articles_v_locales",
  {
    version_title: varchar("version_title"),
    version_body: jsonb("version_body"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_articles_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_articles_v.id],
      name: "_articles_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products = pgTable(
  "products",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug"),
    priceCLP: numeric("price_c_l_p", { mode: "number" }),
    stockStatus:
      enum_products_stock_status("stock_status").default("available"),
    imageUrl: varchar("image_url"),
    sourceUrl: varchar("source_url"),
    sourceUpdatedAt: timestamp("source_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_products_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("products_slug_idx").on(columns.slug),
    index("products_updated_at_idx").on(columns.updatedAt),
    index("products_created_at_idx").on(columns.createdAt),
    index("products__status_idx").on(columns._status),
  ],
);

export const products_locales = pgTable(
  "products_locales",
  {
    title: varchar("title"),
    body: jsonb("body"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("products_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _products_v = pgTable(
  "_products_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => products.id, {
      onDelete: "set null",
    }),
    version_slug: varchar("version_slug"),
    version_priceCLP: numeric("version_price_c_l_p", { mode: "number" }),
    version_stockStatus: enum__products_v_version_stock_status(
      "version_stock_status",
    ).default("available"),
    version_imageUrl: varchar("version_image_url"),
    version_sourceUrl: varchar("version_source_url"),
    version_sourceUpdatedAt: timestamp("version_source_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__products_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__products_v_published_locale("published_locale"),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => [
    index("_products_v_parent_idx").on(columns.parent),
    index("_products_v_version_version_slug_idx").on(columns.version_slug),
    index("_products_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_products_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_products_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_products_v_created_at_idx").on(columns.createdAt),
    index("_products_v_updated_at_idx").on(columns.updatedAt),
    index("_products_v_snapshot_idx").on(columns.snapshot),
    index("_products_v_published_locale_idx").on(columns.publishedLocale),
    index("_products_v_latest_idx").on(columns.latest),
    index("_products_v_autosave_idx").on(columns.autosave),
  ],
);

export const _products_v_locales = pgTable(
  "_products_v_locales",
  {
    version_title: varchar("version_title"),
    version_body: jsonb("version_body"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("_products_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_products_v.id],
      name: "_products_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    membershipsID: integer("memberships_id"),
    placesID: integer("places_id"),
    articlesID: integer("articles_id"),
    productsID: integer("products_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_memberships_id_idx").on(
      columns.membershipsID,
    ),
    index("payload_locked_documents_rels_places_id_idx").on(columns.placesID),
    index("payload_locked_documents_rels_articles_id_idx").on(
      columns.articlesID,
    ),
    index("payload_locked_documents_rels_products_id_idx").on(
      columns.productsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["membershipsID"]],
      foreignColumns: [memberships.id],
      name: "payload_locked_documents_rels_memberships_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["placesID"]],
      foreignColumns: [places.id],
      name: "payload_locked_documents_rels_places_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["productsID"]],
      foreignColumns: [products.id],
      name: "payload_locked_documents_rels_products_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings = pgTable("site_settings", {
  id: serial("id").primaryKey(),
  brandName: varchar("brand_name").notNull().default("Community"),
  siteDescription: varchar("site_description").default(
    "A platform for community connection and shared knowledge.",
  ),
  defaultLocale: varchar("default_locale").default("en"),
  lang: varchar("lang").default("en"),
  instagramUrl: varchar("instagram_url"),
  whatsappUrl: varchar("whatsapp_url"),
  memberIdentifierType: enum_site_settings_member_identifier_type(
    "member_identifier_type",
  ).default("generic"),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const home_page = pgTable(
  "home_page",
  {
    id: serial("id").primaryKey(),
    heroVideo: integer("hero_video_id").references(() => media.id, {
      onDelete: "set null",
    }),
    heroVideoAlt: varchar("hero_video_alt").default("Featured community video"),
    _status: enum_home_page_status("_status").default("draft"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("home_page_hero_video_idx").on(columns.heroVideo),
    index("home_page__status_idx").on(columns._status),
  ],
);

export const _home_page_v = pgTable(
  "_home_page_v",
  {
    id: serial("id").primaryKey(),
    version_heroVideo: integer("version_hero_video_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_heroVideoAlt: varchar("version_hero_video_alt").default(
      "Featured community video",
    ),
    version__status:
      enum__home_page_v_version_status("version__status").default("draft"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__home_page_v_published_locale("published_locale"),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => [
    index("_home_page_v_version_version_hero_video_idx").on(
      columns.version_heroVideo,
    ),
    index("_home_page_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_home_page_v_created_at_idx").on(columns.createdAt),
    index("_home_page_v_updated_at_idx").on(columns.updatedAt),
    index("_home_page_v_snapshot_idx").on(columns.snapshot),
    index("_home_page_v_published_locale_idx").on(columns.publishedLocale),
    index("_home_page_v_latest_idx").on(columns.latest),
    index("_home_page_v_autosave_idx").on(columns.autosave),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_memberships = relations(memberships, () => ({}));
export const relations__memberships_v = relations(
  _memberships_v,
  ({ one }) => ({
    parent: one(memberships, {
      fields: [_memberships_v.parent],
      references: [memberships.id],
      relationName: "parent",
    }),
  }),
);
export const relations_places_locales = relations(
  places_locales,
  ({ one }) => ({
    _parentID: one(places, {
      fields: [places_locales._parentID],
      references: [places.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_places = relations(places, ({ many }) => ({
  _locales: many(places_locales, {
    relationName: "_locales",
  }),
}));
export const relations__places_v_locales = relations(
  _places_v_locales,
  ({ one }) => ({
    _parentID: one(_places_v, {
      fields: [_places_v_locales._parentID],
      references: [_places_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__places_v = relations(_places_v, ({ one, many }) => ({
  parent: one(places, {
    fields: [_places_v.parent],
    references: [places.id],
    relationName: "parent",
  }),
  _locales: many(_places_v_locales, {
    relationName: "_locales",
  }),
}));
export const relations_articles_locales = relations(
  articles_locales,
  ({ one }) => ({
    _parentID: one(articles, {
      fields: [articles_locales._parentID],
      references: [articles.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_articles = relations(articles, ({ many }) => ({
  _locales: many(articles_locales, {
    relationName: "_locales",
  }),
}));
export const relations__articles_v_locales = relations(
  _articles_v_locales,
  ({ one }) => ({
    _parentID: one(_articles_v, {
      fields: [_articles_v_locales._parentID],
      references: [_articles_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__articles_v = relations(
  _articles_v,
  ({ one, many }) => ({
    parent: one(articles, {
      fields: [_articles_v.parent],
      references: [articles.id],
      relationName: "parent",
    }),
    _locales: many(_articles_v_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_products_locales = relations(
  products_locales,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_locales._parentID],
      references: [products.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_products = relations(products, ({ many }) => ({
  _locales: many(products_locales, {
    relationName: "_locales",
  }),
}));
export const relations__products_v_locales = relations(
  _products_v_locales,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_locales._parentID],
      references: [_products_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__products_v = relations(
  _products_v,
  ({ one, many }) => ({
    parent: one(products, {
      fields: [_products_v.parent],
      references: [products.id],
      relationName: "parent",
    }),
    _locales: many(_products_v_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    membershipsID: one(memberships, {
      fields: [payload_locked_documents_rels.membershipsID],
      references: [memberships.id],
      relationName: "memberships",
    }),
    placesID: one(places, {
      fields: [payload_locked_documents_rels.placesID],
      references: [places.id],
      relationName: "places",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: "products",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings = relations(site_settings, () => ({}));
export const relations_home_page = relations(home_page, ({ one }) => ({
  heroVideo: one(media, {
    fields: [home_page.heroVideo],
    references: [media.id],
    relationName: "heroVideo",
  }),
}));
export const relations__home_page_v = relations(_home_page_v, ({ one }) => ({
  version_heroVideo: one(media, {
    fields: [_home_page_v.version_heroVideo],
    references: [media.id],
    relationName: "version_heroVideo",
  }),
}));

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_users_role: typeof enum_users_role;
  enum_places_access_type: typeof enum_places_access_type;
  enum_places_status: typeof enum_places_status;
  enum__places_v_version_access_type: typeof enum__places_v_version_access_type;
  enum__places_v_version_status: typeof enum__places_v_version_status;
  enum__places_v_published_locale: typeof enum__places_v_published_locale;
  enum_articles_difficulty: typeof enum_articles_difficulty;
  enum_articles_status: typeof enum_articles_status;
  enum__articles_v_version_difficulty: typeof enum__articles_v_version_difficulty;
  enum__articles_v_version_status: typeof enum__articles_v_version_status;
  enum__articles_v_published_locale: typeof enum__articles_v_published_locale;
  enum_products_stock_status: typeof enum_products_stock_status;
  enum_products_status: typeof enum_products_status;
  enum__products_v_version_stock_status: typeof enum__products_v_version_stock_status;
  enum__products_v_version_status: typeof enum__products_v_version_status;
  enum__products_v_published_locale: typeof enum__products_v_published_locale;
  enum_site_settings_member_identifier_type: typeof enum_site_settings_member_identifier_type;
  enum_home_page_status: typeof enum_home_page_status;
  enum__home_page_v_version_status: typeof enum__home_page_v_version_status;
  enum__home_page_v_published_locale: typeof enum__home_page_v_published_locale;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  memberships: typeof memberships;
  _memberships_v: typeof _memberships_v;
  places: typeof places;
  places_locales: typeof places_locales;
  _places_v: typeof _places_v;
  _places_v_locales: typeof _places_v_locales;
  articles: typeof articles;
  articles_locales: typeof articles_locales;
  _articles_v: typeof _articles_v;
  _articles_v_locales: typeof _articles_v_locales;
  products: typeof products;
  products_locales: typeof products_locales;
  _products_v: typeof _products_v;
  _products_v_locales: typeof _products_v_locales;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings: typeof site_settings;
  home_page: typeof home_page;
  _home_page_v: typeof _home_page_v;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_memberships: typeof relations_memberships;
  relations__memberships_v: typeof relations__memberships_v;
  relations_places_locales: typeof relations_places_locales;
  relations_places: typeof relations_places;
  relations__places_v_locales: typeof relations__places_v_locales;
  relations__places_v: typeof relations__places_v;
  relations_articles_locales: typeof relations_articles_locales;
  relations_articles: typeof relations_articles;
  relations__articles_v_locales: typeof relations__articles_v_locales;
  relations__articles_v: typeof relations__articles_v;
  relations_products_locales: typeof relations_products_locales;
  relations_products: typeof relations_products;
  relations__products_v_locales: typeof relations__products_v_locales;
  relations__products_v: typeof relations__products_v;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings: typeof relations_site_settings;
  relations_home_page: typeof relations_home_page;
  relations__home_page_v: typeof relations__home_page_v;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
